* autofix

Code and comment fixes for emacs-lisp packages.

** Requirements
+ Emacs >= 27.1
+ finder (optional)
+ package-lint

** Installation

*** Manually

Download repository and it to your load path in your init file:

#+begin_src elisp :eval no

(add-to-list 'load-path "/path/to/autofix)

(require 'autofix)

#+end_src

*** With use-package and straight

#+begin_src elisp :eval no

(use-package autofix
	:straight (autofix
			       :repo "KarimAziev/autofix"
			       :type git
			       :host github)
	:bind ((:map autofix-multi-completion-map
			         ("C-<return>" . autofix-throw-done)
			         ("C-M-j" . autofix-throw-done)))
	:commands (autofix
			       autofix-function-name-quoting
			       autofix-footer
			       autofix-remove-unused-declarations
			       autofix-header
			       autofix-autoloads
			       autofix-commentary
			       autofix-code-comment
			       autofix-header-first-line
			       autofix-scan-extract-all-docs
			       autofix-annotate-buffer
			       autofix-url
			       autofix-copyright
			       autofix-keywords
			       autofix-header-body-comment
			       autofix-package-requires
			       autofix-version
			       autofix-update-version
			       autofix-author))

#+end_src

** Minor mode

*** ~autofix-mode~
Runs ~autofix~ on file save when this mode is turned on.

** Commands
*** Fix all
+ ~autofix~
Apply all code and comments fixes. Code fixes includes auto adding autoload comments before all interactive commmands and removing unused (declare-function ...) forms. Comments fixes includes fixes for file headers, package headers, footer etc.

*** Fix file footer
+ ~autofix-footer~
Add of fix file footer (provide 'filename) with comment ends here.

*** Fix header comments

+ ~autofix-header~
Apply all header fixes for header comments except ~autofix-annotate-buffer~.

+ ~autofix-annotate-buffer~
Add annotatations in header comment section. Annotations includes commands, custom variables.

+ ~autofix-header-first-line~
Fix or create the first comment line in the header.

+ ~autofix-commentary~
Add Commentary section in current buffer if none.

+ ~autofix-code-comment~
Add Code comment to the end of header block.

+ ~autofix-url~
Return string with generated url.

+ ~autofix-copyright~
Prompt and fix or make new copyright.

+ ~autofix-keywords~
Add or fix package keywords.

+ ~autofix-header-body-comment~
Add additional comments after package headers. Default vaiue is comment starting with "This file is NOT part of GNU Emacs..."), To change the value customize the variable ~autofix-comment-section-body~.

+ ~autofix-package-requires~
Add or fix package requires section.

+ ~autofix-version~
Add or fix package version.

+ ~autofix-author~
Add current user as new author to existing or new author section.

*** Code fixes
+ ~autofix-autoloads~
Add autoload comments before all interactive functions in buffer.
+ ~autofix-remove-unused-declarations~
Removed unused declared functions.
+ ~autofix-function-name-quoting~
Add a sharp quote (=#'=) when quoting function names. For example, such code:

#+begin_src emacs-lisp
(mapcar 'car '((a . 2) (b . 2) (c . 3)))
#+end_src

Transforms to:

#+begin_src emacs-lisp
(mapcar #'car '((a . 2) (b . 2) (c . 3)))
#+end_src

** Customization

+ ~autofix-ignored-file-patterns~
List of file name bases to ignore.

+ ~autofix-user-fullname~
User email to add in header section.

+ ~autofix-user-email~
User email to add in header section. Can be string, variable or function. Function will be called without args and should return string.

+ ~autofix-comment-section-body~
Static text for adding in header comment section. It doesn't includes dynamic variables such author, year etc.
