* autofix
Code and comment fixes, generating documentation for emacs-lisp packages.
** Installation

*** Manually

Download repository and it to your load path in your init file:

#+begin_src elisp :eval no

(add-to-list 'load-path "/path/to/autofix/")

(require 'autofix)

#+end_src

*** With use-package and straight

#+begin_src elisp :eval no

(use-package autofix
  :straight (:repo "KarimAziev/autofix" :type git :host github)
  :commands (autofix
             autofix-footer
             autofix-header
             autofix-commentary
             autofix-code-comment
             autofix-header-first-line
             autofix-copy-org-annotations
             autofix-show-org-annotations
             autofix-scan-extract-all-docs
             autofix-url
             autofix-copyright
             autofix-keywords
             autofix-header-body-comment
             autofix-package-requires
             autofix-version
             autofix-author
             autofix-annotate-buffer
             autofix-remove-unused-declarations
             autofix-autoloads))

#+end_src

** Commands
*** Fix all
+ ~autofix~
Apply all code and comments fixes. Code fixes includes auto adding autoload comments before all interactive commmands and removing unused (declare-function ...) forms. Comments fixes includes fixes for file headers, package headers, footer etc.

*** Fix file footer
+ ~autofix-footer~
Add of fix file footer (provide 'filename) with comment ends here.

*** Fix header comments

+ ~autofix-header~
Apply all header fixes for header comments except ~autofix-annotate-buffer~.

+ ~autofix-annotate-buffer~
Add annotatations in header comment section. Annotations includes commands, custom variables.

+ ~autofix-header-first-line~
Fix or create the first comment line in the header.

+ ~autofix-commentary~
Add Commentary section in current buffer if none.

+ ~autofix-code-comment~
Add Code comment to the end of header block.

+ ~autofix-url~
Return string with generated url.

+ ~autofix-copyright~
Prompt and fix or make new copyright.

+ ~autofix-keywords~
Add or fix package keywords.

+ ~autofix-header-body-comment~
Add additional comments after package headers. Default vaiue is comment starting with "This file is NOT part of GNU Emacs..."), To change the value customize the variable ~autofix-comment-section-body~.

+ ~autofix-package-requires~
Add or fix package requires section.

+ ~autofix-version~
Add or fix package version.

+ ~autofix-author~
Add current user as new author to existing or new author section.

*** Code fixes
+ ~autofix-autoloads~
Add autoload comments before all interactive functions in buffer.
+ ~autofix-remove-unused-declarations~
Removed unused declared functions.


*** Generate documentation
+ ~autofix-copy-org-annotations~
Copy org annotations of items in buffer.

+ ~autofix-show-org-annotations~
Show annotations as org list items.

+ ~autofix-scan-extract-all-docs~
Return string with all docs in all buffer. If called interactively also copies it.


** Customization

+ ~autofix-ignored-file-patterns~
List of file name bases to ignore.

+ ~autofix-user-fullname~
User email to add in header section.

+ ~autofix-user-email~
User email to add in header section. Can be string, variable or function. Function will be called without args and should return string.

+ ~autofix-comment-section-body~
Static text for adding in header comment section. It doesn't includes dynamic variables such author, year etc.
